### PR TITLE
fix a compilation error introduced in 077a818.

### PR DESCRIPTION
**Pull request by raulk**

### CODE REVIEW

**Comment by vyzo** [comment]
Still failing to compile:
```
*** go build github.com/libp2p/go-libp2p

# github.com/libp2p/go-libp2p/p2p/host/basic

p2p/host/basic/basic_host.go:379:30: cannot use *sr (type record.Envelope) as type *record.Envelope in assignment

```

**Comment by raulk** [comment]
Tests fail because of the races that will be fixed in https://github.com/libp2p/go-libp2p/pull/907.
