### ISSUE TITLE
Fails to build on FreeBSD: decay.go:41:18: undefined: atomic.Pointer

### ISSUE THREAD

**Issue by yurivict** [libp2p/go-libp2p#2377]
```
vendor/github.com/libp2p/go-libp2p/p2p/net/connmgr/decay.go:41:18: undefined: atomic.Pointer
vendor/github.com/libp2p/go-libp2p/p2p/net/connmgr/decay.go:296:16: undefined: atomic.Bool
vendor/github.com/libp2p/go-libp2p/p2p/net/connmgr/connmgr.go:41:19: undefined: atomic.Int32
```

Built as part of the https://github.com/ipfs/ipget project.

FreeBSD 13.2

**Comment by marten-seemann** [comment]
I suspect this is because you're trying to build with a Go version before Go 1.19.
