### ISSUE TITLE
[bug]host.go:68:28: too many arguments in call to libp2p.ConnectionManager

### ISSUE THREAD

**Issue by hktalent** [libp2p/go-libp2p#1366]
example:
$ go version
go version go1.18 darwin/amd64
$ go build  host.go                          
```
# command-line-arguments
./host.go:68:28: too many arguments in call to libp2p.ConnectionManager
	have (*"github.com/libp2p/go-libp2p-connmgr".BasicConnMgr, error)
	want ("github.com/libp2p/go-libp2p-core/connmgr".ConnManager)
./host.go:71:4: cannot use time.Minute (constant 60000000000 of type time.Duration) as type "github.com/libp2p/go-libp2p-connmgr".Option in argument to connmgr.NewConnManager
```

**Comment by marten-seemann** [comment]
Works on my machine.

**Comment by hktalent** [comment]
$ pwd
```
go-libp2p/examples/libp2p-host
$ go build host.go
# github.com/lucas-clemente/quic-go/internal/qtls
../../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.24.0/internal/qtls/go118.go:6:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
 libp2p-host $ cd ..
 examples $ cd ..
 go-libp2p $ go build examples/libp2p-host/host.go 
examples/libp2p-host/host.go:9:2: no required module provides package github.com/libp2p/go-libp2p-connmgr; to add it:
	go get github.com/libp2p/go-libp2p-connmgr
examples/libp2p-host/host.go:13:2: no required module provides package github.com/libp2p/go-libp2p-kad-dht; to add it:
	go get github.com/libp2p/go-libp2p-kad-dht
 go-libp2p $    go get github.com/libp2p/go-libp2p-connmgr
go: added github.com/libp2p/go-libp2p-connmgr v0.3.1
 go-libp2p $    go get github.com/libp2p/go-libp2p-kad-dht
go: added github.com/libp2p/go-libp2p-kad-dht v0.15.0
 go-libp2p $ go build examples/libp2p-host/host.go        
# command-line-arguments
examples/libp2p-host/host.go:68:28: too many arguments in call to libp2p.ConnectionManager
	have (*"github.com/libp2p/go-libp2p-connmgr".BasicConnMgr, error)
	want ("github.com/libp2p/go-libp2p-core/connmgr".ConnManager)
examples/libp2p-host/host.go:71:4: cannot use time.Minute (constant 60000000000 of type time.Duration) as type "github.com/libp2p/go-libp2p-connmgr".Option in argument to connmgr.NewConnManager
```
